### ISSUE TITLE
I think we need to use StandardJS as standard for our coding standard

### ISSUE THREAD

**Issue by ezesundayeze** [Ani-Emmanuel/ASLANG#2]
[Standard](https://standardjs.com/rules.html)

The beauty of JavaScript Standard Style is that it's simple. No one wants to maintain multiple hundred-line style configuration files for every module/project they work on. Enough of this madness!

This module saves you (and others!) time in three ways:

No configuration. The easiest way to enforce consistent style in your project. Just drop it in.
Automatically format code. Just run standard --fix and say goodbye to messy or inconsistent code.
Catch style issues & programmer errors early. Save precious code review time by eliminating back-and-forth between reviewer & contributor.
Adopting standard style means ranking the importance of code clarity and community conventions higher than personal style. This might not make sense for 100% of projects and development cultures, however open source can be a hostile place for newbies. Setting up clear, automated contributor expectations makes a project healthier.

For more info, see the conference talk "Write Perfect Code with Standard and ESLint". In this talk, you'll learn about linting, when to use standard versus eslint, and how prettier compares to standard.

I think this will be a good one for us to stay consistent.

**Comment by Ani-Emmanuel** [comment]
Ok StandardJs is a good development tool

**Comment by ezesundayeze** [comment]
Cool. So, can you add this to the project?
